// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://feomlhatohojwytazkxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlb21saGF0b2hvand5dGF6a3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NTc3MDUsImV4cCI6MjA2MzEzMzcwNX0.wQ-mDmhCbUUp3KA1wpgyQPYWTfu1fqOPFfb4eXCbzJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);